name: C CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install libsdl2-dev
    - uses: actions/checkout@v3
    - name: make
      run: make
