name: C CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.2
      with:
        type: 'zip'
        filename: 'release-linux.zip'
        path: res/ game
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-linux"
        prerelease: false
        title: "Latest Build"
        files: |
          release-linux.zip
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
         update: true
         install: >-
            base-devel
            git
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-SDL2
      - name: check folder
        run: ls

      - name: build project
        run: make game
